#!/bin/bash

echo "🐦 Twitter App Access Check"
echo "=========================="
echo ""

echo "📋 To check if your Twitter app needs elevated access:"
echo ""
echo "1. Go to https://developer.twitter.com/en/portal/dashboard"
echo "2. Select your app"
echo "3. Look for 'App permissions' section"
echo "4. Check if you see any warnings about 'Elevated access required'"
echo ""
echo "🔍 Common Issues:"
echo "-----------------"
echo ""
echo "❌ **App needs elevated access**:"
echo "   - If you see 'Elevated access required' or similar message"
echo "   - You need to apply for elevated access"
echo "   - Go to https://developer.twitter.com/en/portal/products/elevated"
echo "   - Apply for elevated access for your app"
echo ""
echo "❌ **API keys mismatch**:"
echo "   - Make sure you're using the correct API Key and Secret"
echo "   - These should be from the 'Keys and tokens' tab"
echo "   - Not the Bearer Token"
echo ""
echo "❌ **App not approved**:"
echo "   - Your app might be in development mode"
echo "   - Check if you need to submit for review"
echo ""
echo "✅ **Quick Fixes to Try**:"
echo "-------------------------"
echo ""
echo "1. **Restart everything**:"
echo "   ./scripts/restart-dev.sh"
echo ""
echo "2. **Clear browser cache**:"
echo "   - Open incognito/private window"
echo "   - Try the OAuth flow again"
echo ""
echo "3. **Check Supabase Dashboard**:"
echo "   - Go to your Supabase Dashboard"
echo "   - Authentication → Providers → Twitter"
echo "   - Make sure it's enabled"
echo "   - Try disabling and re-enabling it"
echo ""
echo "4. **Test with different browser**:"
echo "   - Try Chrome, Firefox, or Safari"
echo "   - Sometimes browser extensions interfere"
echo ""
echo "🔧 **Debug Commands**:"
echo "---------------------"
echo ""
echo "Check environment: ./scripts/check-env.sh"
echo "Debug OAuth: ./scripts/debug-oauth.sh"
echo "Get callback URLs: ./scripts/get-supabase-url.sh"
echo ""
echo "📝 **Next Steps**:"
echo "=================="
echo ""
echo "1. Check if your Twitter app needs elevated access"
echo "2. Verify API keys are correct"
echo "3. Try the OAuth flow in incognito mode"
echo "4. Check Supabase Dashboard Twitter provider settings"
echo "5. If still failing, try creating a new Twitter app" 