#!/bin/bash

echo "🔍 Twitter OAuth Headers & Token Debug"
echo "======================================"
echo ""

echo "📋 The issue might be with OAuth 2.0 vs OAuth 1.0a:"
echo ""
echo "❌ **Common Twitter OAuth Issues**:"
echo "-----------------------------------"
echo ""
echo "1. **OAuth 2.0 vs OAuth 1.0a Mismatch**:"
echo "   - Twitter supports both OAuth 1.0a and OAuth 2.0"
echo "   - Supabase Auth might be using OAuth 2.0"
echo "   - Your Twitter app might be configured for OAuth 1.0a"
echo ""
echo "2. **Required Headers for Twitter OAuth 2.0**:"
echo "   - Authorization: Bearer <access_token>"
echo "   - Content-Type: application/json"
echo "   - Accept: application/json"
echo ""
echo "3. **Required Headers for Twitter OAuth 1.0a**:"
echo "   - Authorization: OAuth oauth_consumer_key=\"...\", oauth_token=\"...\""
echo "   - Content-Type: application/x-www-form-urlencoded"
echo ""
echo "🔧 **Debug Steps**:"
echo "-------------------"
echo ""
echo "1. **Check Twitter App OAuth Settings**:"
echo "   - Go to Twitter Developer Portal"
echo "   - Check if 'OAuth 2.0' is enabled"
echo "   - Verify 'App permissions' is 'Read and Write'"
echo "   - Make sure 'Type of App' is 'Web App, Automated App or Bot'"
echo ""
echo "2. **Check Supabase Auth Configuration**:"
echo "   - Supabase Auth uses OAuth 2.0 by default"
echo "   - Make sure your Twitter app supports OAuth 2.0"
echo "   - Check if you need to enable OAuth 2.0 in your Twitter app"
echo ""
echo "3. **Verify Environment Variables**:"
echo "   - SUPABASE_AUTH_EXTERNAL_TWITTER_CLIENT_ID (API Key)"
echo "   - SUPABASE_AUTH_EXTERNAL_TWITTER_SECRET (API Secret)"
echo "   - These should be from 'Keys and tokens' tab"
echo ""
echo "4. **Test OAuth Flow**:"
echo "   - Visit: http://localhost:3000/test-twitter-access"
echo "   - Check browser network tab for request headers"
echo "   - Look for any 401/403 errors"
echo ""
echo "🔍 **Common Solutions**:"
echo "----------------------"
echo ""
echo "✅ **Enable OAuth 2.0 in Twitter App**:"
echo "   1. Go to Twitter Developer Portal"
echo "   2. Select your app"
echo "   3. Go to 'App settings'"
echo "   4. Enable 'OAuth 2.0' if available"
echo "   5. Add callback URLs for OAuth 2.0"
echo ""
echo "✅ **Check API Keys**:"
echo "   - Make sure you're using API Key and Secret"
echo "   - Not Bearer Token or Access Token"
echo "   - These should be from 'Keys and tokens' tab"
echo ""
echo "✅ **Verify Callback URLs**:"
echo "   - https://ghbaaexxytbvmbimmrkj.supabase.co/auth/v1/callback"
echo "   - http://localhost:3000/auth/callback/supabase"
echo ""
echo "✅ **Check App Permissions**:"
echo "   - Should be 'Read and Write'"
echo "   - Not 'Read only'"
echo ""
echo "🔧 **Debug Commands**:"
echo "--------------------"
echo ""
echo "Check environment: ./scripts/check-env.sh"
echo "Debug OAuth: ./scripts/debug-oauth.sh"
echo "Test Twitter access: ./scripts/check-twitter-access.sh"
echo ""
echo "📝 **Next Steps**:"
echo "=================="
echo ""
echo "1. Enable OAuth 2.0 in your Twitter app"
echo "2. Verify API keys are correct"
echo "3. Test the OAuth flow again"
echo "4. Check browser network tab for errors"
echo "5. If still failing, try creating a new Twitter app" 